spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/company
    username: hradmin
    password: hrpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: debug
    com.zaxxer.hikari.pool.HikariPool: info
server:
  port: 8008
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui
  paths-to-match: /api/**

talk:
  member:
    popular-day: 3  # 실시간 인기 강연 기준일 (ex. 3일 이내 가장 많이 신청한 강연)
    open-day: 7     # 강연 시작 시간 기준, 노출일 (ex. 강연 시작 시간 1주일 전 노출)
    close-day: 1    # 강연 시작 시간 기준, 강연 비노출 시작일 (ex. 강연 시작 시간 1일 후 비노출)
    id-length: 5    # 사번 자릿수